# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VhallSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VhallSDKDemo

  pod 'VHLiveSDK', '6.23.0' # 直播
  pod 'VHLiveSDK_Interactive', '6.23.0' # 互动
  pod 'VHGoodsSDK', '6.23.0' # 商品


  pod 'MJRefresh', '~> 3.7.5'
  pod 'MJExtension', '~> 3.4.1'
  pod 'SDWebImage', '~> 5.14.3'
  pod 'YYText', :git => 'git@github.com:ccccwhj-whj/YYText.git', :tag => '1.0.0'  
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'IQKeyboardManager', '~> 6.5.11'
  pod 'JXCategoryView', '~> 1.6.1'
  pod 'TXScrollLabelView', '~> 1.3.2'
  pod 'GKPhotoBrowser/SD', '~> 2.4.4'
  pod 'Reachability', '~> 3.2'
  pod 'LYEmptyView', '~> 1.3.1'
  pod 'BarrageRenderer', '1.9.1'

  pod 'VHYun_Beautify','1.0.6'
  pod 'FURenderKit','8.3.0'

  target 'VhallSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'VhallSDKDemoUITests' do
    # Pods for testing
    # UI测试
    
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
