# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'VHSDKDemo' do
  pod  'VHLiveSDK' ,'6.3.1'
  pod  'VHLiveSDK_Interactive', '6.3.1'
  pod  'VHYun_Beautify','1.0.6' 
end

