# Uncomment the next line to define a global platform for your project
#
# source 'https://gitlab.vhall.com/guoliang.li/vh_pod_repo.git'
# source 'https://cdn.cocoapods.org'
# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#
# 这里不再指定 Source
#

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

workspace "./VHSDKDemo.xcworkspace"

target 'VHSDKDemo' do
  pod 'GLEnvs'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'VHYun_Beautify', '1.0.6'
end

target 'UIModel' do
  project "../VHSDKUIModel/UIModel.xcodeproj"
  pod 'VHYun_Beautify','1.0.6'
end
